### ISSUE TITLE
allow configuration of more than one file pattern for spec runner locations

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/webpack-jasmine-html-runner-plugin#4]
Currently only one pattern can be defined for the jasmine spec runner file. However in some repositories there are different types and locations of assets that have tests. For example the [LaxarJS/laxar-angular-adapter](https://github.com/LaxarJS/laxar-angular-adapter).
It has tests at the root level for the actual adapter, but also in the folder of each additional artifact type that is part of the repository (e.g. `lib/directives` or `lib/services`). For this case it would be nice to be able to do something like this:

``` js
config.entry = WebpackJasmineHtmlRunnerPlugin.entry(
   './spec/[name]-runner.js' ,
   './lib/[name]/spec/spec-runner.js'
);
```

Additionally it is currently mandatory to have a `[name]` part in the pattern, to denote the target within `spec-output` for the generated HTML spec runner. In the case above this leads to a folder called `spec` for the root artifacts alongside the well named lib artifacts (i.e. `directives` and `services`). Perhaps it would be better to ditch this altogether and reflect the directory tree the specs were read from in the `spec-output` folder. This would prevent from any ambiguities.
For this case: 

```
spec-output
   \ spec/spec-runner.html
   \ lib
      \ directives
          spec/spec-runner.html
      \ services
          spec/spec-runner.html
```

**Comment by x1B** [comment]
Implemented on `master` (`v0.4.0`).

### BREAKING CHANGE

Multiple patterns may now be specified when generating entry points for spec runners.

For this reason the `[name]` placeholder now deprecated (it is now simply replaced by `**`) and does no longer determine the output path for a spec runner, as it might lead to conflicts when using multiple patterns. Instead, the source path matched by the pattern is simply appended to `spec-output` to calculate the output path, so that source tree and result tree now match up.
